# Generated by Django 5.2.15 on 2026-07-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayt', '0002_person_pointaward_tokenaward_delete_pupil'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='class_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='student_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
